# **Phase 1: Sélection du Dataset**
*Chargement des données*

In [4]:
import pandas as pd
import numpy as np

In [5]:
# Load dataset
df = pd.read_csv("healthcare_dataset.csv")

In [6]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [ ]:
print("Shape (rows, columns):", df.shape)

Shape (rows, columns): (55500, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

# **Phase 2 : Profilage et Exploration**

# Analyse Manuelle

*Changer type des attributs*

In [ ]:
# Convert dates
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.4+ MB

*Calculer les valeurs manquantes*

In [ ]:
# Missing values
missing_df = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
}).sort_values("missing_percent", ascending=False)

missing_df

                    missing_count  missing_percent
Name                            0              0.0
Age                             0              0.0
Gender                          0              0.0
Blood Type                      0              0.0
Medical Condition               0              0.0
Date of Admission               0              0.0
Doctor                          0              0.0
Hospital                        0              0.0
Insurance Provider              0              0.0
Billing Amount                  0              0.0
Room Number                     0              0.0
Admission Type                  0              0.0
Discharge Date                  0              0.0
Medication                      0              0.0
Test Results                    0              0.0

*Duplicates patients*

In [ ]:
duplicates = df[df.duplicated(
    subset=["Name", "Date of Admission"], keep=False
)]
duplicates.shape

(11000, 15)

In [ ]:
duplicates_sorted = (
    df[df.duplicated(subset=["Name", "Date of Admission"], keep=False)]
    .sort_values(by=["Name", "Date of Admission"])
)

duplicates_sorted.head(20)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
17083,AARon smITh,79,Male,A-,Cancer,2019-11-21,Gina Jacobs,Weber-Warren,Medicare,21879.766348,155,Emergency,2019-12-20,Ibuprofen,Inconclusive
54393,AARon smITh,81,Male,A-,Cancer,2019-11-21,Gina Jacobs,Weber-Warren,Medicare,21879.766348,155,Emergency,2019-12-20,Ibuprofen,Inconclusive
3040,AAron ArCHER,47,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive
54112,AAron ArCHER,49,Female,B-,Cancer,2021-01-10,Cynthia Villanueva,"Montes Case and Mendez,",Medicare,10602.077185,108,Urgent,2021-01-17,Paracetamol,Inconclusive
40305,ABIGAiL wateRS,34,Female,O+,Asthma,2023-11-13,Sandra Boyer,"Rogers Martin Prince, and",UnitedHealthcare,3121.196138,421,Elective,2023-11-22,Aspirin,Inconclusive
52111,ABIGAiL wateRS,35,Female,O+,Asthma,2023-11-13,Sandra Boyer,"Rogers Martin Prince, and",UnitedHealthcare,3121.196138,421,Elective,2023-11-22,Aspirin,Inconclusive
2018,ABIgAIL tucKeR,66,Male,B+,Cancer,2020-08-10,Christopher Avery,Perry and Sons,Blue Cross,1773.455716,480,Elective,2020-08-26,Paracetamol,Normal
52517,ABIgAIL tucKeR,68,Male,B+,Cancer,2020-08-10,Christopher Avery,Perry and Sons,Blue Cross,1773.455716,480,Elective,2020-08-26,Paracetamol,Normal
42407,ABIgaIL YOung,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
54285,ABIgaIL YOung,41,Female,O+,Hypertension,2022-12-15,Edward Kramer,Moore-Mcdaniel,UnitedHealthcare,1983.568297,192,Elective,2023-01-13,Ibuprofen,Normal
7639,ADAm fleTCHEr,75,Male,B-,Arthritis,2021-04-17,Michael Brown,Williamson-Dean,Aetna,43350.207201,373,Elective,2021-05-10,Ibuprofen,Abnormal
53231,ADAm fleTCHEr,73,Male,B-,Arthritis,2021-04-17,Michael Brown,Williamson-Dean,Aetna,43350.207201,373,Elective,2021-05-10,Ibuprofen,Abnormal
23933,ADaM taylOR,68,Female,A-,Cancer,2023-09-04,Veronica Combs,"Walsh, Morris Young and",Blue Cross,41472.066427,162,Emergency,2023-09-16,Penicillin,Inconclusive
51465,ADaM taylOR,63,Female,A-,Cancer,2023-09-04,Veronica Combs,"Walsh, Morris Young and",Blue Cross,41472.066427,162,Emergency,2023-09-16,Penicillin,Inconclusive
38403,ADam Mccoy,67,Female,A-,Arthritis,2023-08-17,Katherine Hudson,"Smith Escobar, and Curtis",Blue Cross,7597.041254,126,Elective,2023-08-21,Paracetamol,Inconclusive
55396,ADam Mccoy,64,Female,A-,Arthritis,2023-08-17,Katherine Hudson,"Smith Escobar, and Curtis",Blue Cross,7597.041254,126,Elective,2023-08-21,Paracetamol,Inconclusive
24862,ADriAN HAney,38,Female,B-,Diabetes,2022-10-21,Bethany Patrick,PLC Powers,Cigna,20776.546824,457,Urgent,2022-10-25,Ibuprofen,Inconclusive
52085,ADriAN HAney,36,Female,B-,Diabetes,2022-10-21,Bethany Patrick,PLC Powers,Cigna,20776.546824,457,Urgent,2022-10-25,Ibuprofen,Inconclusive
5105,ALAN LEViNE,28,Female,B-,Diabetes,2019-07-02,Evan Montgomery,Cole Ltd,Medicare,21405.610717,224,Elective,2019-07-21,Lipitor,Normal
53341,ALAN LEViNE,32,Female,B-,Diabetes,2019-07-02,Evan Montgomery,Cole Ltd,Medicare,21405.610717,224,Elective,2019-07-21,Lipitor,Normal

*Patients avec trop de réadmissions rapprochées*

si Name apparaît plusieurs fois sur une courte période

In [ ]:
df_sorted = df.sort_values(["Name", "Date of Admission"])

df_sorted["Prev_Discharge"] = df_sorted.groupby("Name")["Discharge Date"].shift(1)

df_sorted["Days_Between"] = ( df_sorted["Date of Admission"] - df_sorted["Prev_Discharge"] ).dt.days

readmission_anomalies = df_sorted[df_sorted["Days_Between"] < 7]
readmission_anomalies.shape

(5500, 17)

In [ ]:
result = readmission_anomalies.sort_values(
    ["Name", "Date of Admission"]
)
cols_to_view = [
    "Name",
    "Date of Admission",
    "Discharge Date",
    "Prev_Discharge",
    "Days_Between",
    "Medical Condition",
    "Admission Type",
    "Hospital"
]

result[cols_to_view].head(20)

,Name,Date of Admission,Discharge Date,Prev_Discharge,Days_Between,Medical Condition,Admission Type,Hospital
54393,AARon smITh,2019-11-21,2019-12-20,2019-12-20,-29.0,Cancer,Emergency,Weber-Warren
54112,AAron ArCHER,2021-01-10,2021-01-17,2021-01-17,-7.0,Cancer,Urgent,"Montes Case and Mendez,"
52111,ABIGAiL wateRS,2023-11-13,2023-11-22,2023-11-22,-9.0,Asthma,Elective,"Rogers Martin Prince, and"
52517,ABIgAIL tucKeR,2020-08-10,2020-08-26,2020-08-26,-16.0,Cancer,Elective,Perry and Sons
54285,ABIgaIL YOung,2022-12-15,2023-01-13,2023-01-13,-29.0,Hypertension,Elective,Moore-Mcdaniel
53231,ADAm fleTCHEr,2021-04-17,2021-05-10,2021-05-10,-23.0,Arthritis,Elective,Williamson-Dean
51465,ADaM taylOR,2023-09-04,2023-09-16,2023-09-16,-12.0,Cancer,Emergency,"Walsh, Morris Young and"
55396,ADam Mccoy,2023-08-17,2023-08-21,2023-08-21,-4.0,Arthritis,Elective,"Smith Escobar, and Curtis"
52085,ADriAN HAney,2022-10-21,2022-10-25,2022-10-25,-4.0,Diabetes,Urgent,PLC Powers
53341,ALAN LEViNE,2019-07-02,2019-07-21,2019-07-21,-19.0,Diabetes,Elective,Cole Ltd
51304,ALEXaNdRIa coLon,2022-03-01,2022-03-19,2022-03-19,-18.0,Cancer,Urgent,"Gross, Thompson Smith and"
50910,ALEXanDrA HernANdeZ,2023-11-14,2023-12-12,2023-12-12,-28.0,Arthritis,Urgent,"and Mosley Williams Cameron,"
50426,ALExIs garCIa,2019-07-18,2019-07-19,2019-07-19,-1.0,Arthritis,Elective,"and Hicks, Walker Jordan"
51934,ALExa KeNneDY,2023-09-01,2023-09-17,2023-09-17,-16.0,Cancer,Elective,"Vega Durham Morrison, and"
52532,ALExanDeR maRTinez,2022-09-10,2022-09-11,2022-09-11,-1.0,Hypertension,Urgent,Johnson Group
51207,ALExanDer anDerSOn,2023-06-07,2023-06-27,2023-06-27,-20.0,Obesity,Elective,"Bush Fields and Francis,"
50770,ALExanDer wILey,2023-02-15,2023-03-16,2023-03-16,-29.0,Cancer,Elective,"Hill, Krueger and Miller"
51984,ALIcIA NoLAN,2023-05-17,2023-05-21,2023-05-21,-4.0,Obesity,Urgent,Powell-Mcdonald
53104,ALIcia taYLoR,2022-09-18,2022-10-15,2022-10-15,-27.0,Asthma,Elective,Wright LLC
51720,ALLIson HoWaRD,2021-01-14,2021-02-05,2021-02-05,-22.0,Hypertension,Urgent,Jones Sons and

*Âge incohérent*
> (Age < 0 ou Age > 120)

In [ ]:
age_anomalies = df[(df["Age"] < 0) | (df["Age"] > 120)]
age_anomalies.shape

(0, 15)

*Gender incohérent*

> Par ex: Gender = "Male" + Medical Condition = "Pregnancy"

In [ ]:
gender_male_anomalies = df[
    (df["Gender"] == "Male") &
    (df["Medical Condition"] == "Pregnancy")
]
gender_male_anomalies.shape

(0, 15)

*Age et Medical Condition incoherences*

L'âge n'est pas compatible avec une condition médicale

> Par ex: Age < 5 mais Medical Condition = “Hypertension”

> Age > 90 mais Admission Type = “Routine”

In [ ]:
age_condition_5 = df[
    (df["Age"] < 5) &
    (df["Medical Condition"].isin(["Hypertension", "Heart Disease"]))
]
age_condition_5.shape

(0, 15)

In [ ]:
age_condition_90 = df[
    (df["Age"] >90 ) &
    (df["Medical Condition"].isin(["Routine"]))
]
age_condition_90.shape

(0, 15)

*Date incohérente (sortie avant admission)*

In [ ]:
date_anomalies = df[df["Discharge Date"] < df["Date of Admission"]]
date_anomalies.shape

(0, 15)

*Durée de séjour anormale*

> Par ex: > 365 jours

In [ ]:
df["Length_of_Stay"] = (df["Discharge Date"] - df["Date of Admission"]).dt.days

long_stay = df[df["Length_of_Stay"] > 365]
long_stay.shape

(0, 16)

*Dates futures (Admission ou Discharge)*

In [ ]:
today = pd.Timestamp.today()

future_dates = df[
    (df["Date of Admission"] > today) |
    (df["Discharge Date"] > today)
]
future_dates.shape

(0, 15)

*Doctor associé à un nombre anormalement élevé de patients*

In [ ]:
doctor_load = df["Doctor"].value_counts()
doctor_anomalies = doctor_load[doctor_load > doctor_load.quantile(0.99)]
doctor_anomalies

Doctor
Michael Smith        27
John Smith           22
Robert Smith         22
Michael Johnson      20
James Smith          20
                     ..
Jessica Lewis         6
Shannon Jones         6
Richard Brown         6
Laura Jones           6
Christopher Perez     6
Name: count, Length: 332, dtype: int64

*Hospital avec facturation moyenne anormale*

In [ ]:
billing_by_hospital = df.groupby("Hospital")["Billing Amount"].mean()

high_billing_hospitals = billing_by_hospital[
    billing_by_hospital > billing_by_hospital.quantile(0.95)
].sort_values(ascending=False)

high_billing_hospitals

Hospital
Hernandez-Morton                 52373.032374
Walker-Garcia                    52170.036854
Ruiz-Anthony                     52154.237722
George-Gonzalez                  52102.240889
Rocha-Carter                     52092.669896
                                     ...
Nelson and Richardson Taylor,    47423.697039
and Campbell Cook Wiggins,       47422.918464
and Schultz Alvarez, Spencer     47418.292654
Weber-Mcpherson                  47417.999804
Knapp, Davis Ortiz and           47417.408377
Name: Billing Amount, Length: 1994, dtype: float64

In [ ]:
low_billing_hospitals = billing_by_hospital[
    billing_by_hospital < billing_by_hospital.quantile(0.05)
].sort_values()

low_billing_hospitals

Hospital
Juarez-Clark                    -2008.492140
Medina and Elliott Stewart,     -1316.618581
Clements-Bowman                 -1277.645337
Lawrence and Cooper Saunders,   -1129.997176
Hunter-Hughes                   -1018.245371
                                    ...
Jackson-Kennedy                  3804.699231
Gonzalez, Ward Hobbs and         3806.486919
Gregory, and Phillips Morales    3806.833899
Lloyd Smith and Miller,          3811.065122
Torres-Lewis                     3811.676580
Name: Billing Amount, Length: 1994, dtype: float64

*Insurance Provider suspects*

In [ ]:
df["Insurance Provider"].value_counts()

Insurance Provider
Cigna               11249
Medicare            11154
UnitedHealthcare    11125
Blue Cross          11059
Aetna               10913
Name: count, dtype: int64

*Insurance Provider avec taux élevé de séjours longs*

In [ ]:
insurance_stay = df.groupby("Insurance Provider")["Length_of_Stay"].mean()
insurance_stay.sort_values(ascending=False)

Insurance Provider
Medicare            15.633046
Blue Cross          15.522109
Cigna               15.485910
UnitedHealthcare    15.455371
Aetna               15.447448
Name: Length_of_Stay, dtype: float64

*Billing Amount négatif ou nul*

In [ ]:
billing_anomalies = df[df["Billing Amount"] <= 0]
billing_anomalies.shape

(108, 16)

In [ ]:
billing_anomalies.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length_of_Stay
132,ashLEy ERIcKSoN,32,Female,AB-,Cancer,2019-11-05,Gerald Hooper,"and Johnson Moore, Branch",Aetna,-502.507813,376,Urgent,2019-11-23,Penicillin,Normal,18
799,CHRisTOPHer wEiss,49,Female,AB-,Asthma,2023-02-16,Kelly Thompson,Hunter-Hughes,Aetna,-1018.245371,204,Elective,2023-03-09,Penicillin,Inconclusive,21
1018,AsHley WaRnER,60,Male,A+,Hypertension,2021-12-21,Andrea Bentley,"and Wagner, Lee Klein",Aetna,-306.364925,426,Elective,2022-01-11,Ibuprofen,Normal,21
1421,JAY galloWaY,74,Female,O+,Asthma,2021-01-20,Debra Everett,Group Peters,Blue Cross,-109.097122,381,Emergency,2021-02-09,Ibuprofen,Abnormal,20
2103,josHUa wilLIamSon,72,Female,B-,Diabetes,2021-03-21,Wendy Ramos,"and Huff Reeves, Dennis",Blue Cross,-576.727907,369,Urgent,2021-04-17,Aspirin,Abnormal,27

*Billing Amount incohérent avec Length of Stay*

In [ ]:
billing_stay_anomalies = df[
    (df["Length_of_Stay"] > 30) &
    (df["Billing Amount"] < df["Billing Amount"].quantile(0.1))
]
billing_stay_anomalies.shape

(0, 16)

*Room Number incohérent*

In [ ]:
room_anomalies = df[
    (df["Room Number"] <= 0) |
    (df["Room Number"] > 10000)
]
room_anomalies.shape

(0, 16)

*Valeurs catégorielles Admissions rares*

In [ ]:
df["Admission Type"].value_counts(normalize=True)

Admission Type
Elective     0.336126
Urgent       0.334703
Emergency    0.329171
Name: proportion, dtype: float64

*Emergency avec séjour nul*
> Cas urgent → rarement sortie immédiate

In [ ]:
emergency_zero_stay = df[
    (df["Admission Type"] == "Emergency") &
    (df["Length_of_Stay"] == 0)
]
emergency_zero_stay.shape

(0, 16)

*Test Results vs Medical Condition*

> Exemple: Medical Condition = "Diabetes" & Test Results = "Normal"

In [ ]:
incoherent_tests_diab = df[
    (df["Medical Condition"] == "Diabetes") &
    (df["Test Results"] == "Normal")
]
incoherent_tests_diab.shape

(3090, 16)

In [ ]:
incoherent_tests_diab.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length_of_Stay
34,NicOlE RodriGUEz,30,Female,AB+,Diabetes,2020-01-17,Lynn Young,Poole Inc,Blue Cross,8408.949354,285,Emergency,2020-02-10,Lipitor,Normal,24
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992.273688,413,Urgent,2020-05-13,Aspirin,Normal,9
68,MicHAEl MillEr,31,Male,B+,Diabetes,2024-02-06,Jonathan Drake,"Clark Brown, and Myers",UnitedHealthcare,35776.815111,489,Emergency,2024-02-10,Penicillin,Normal,4
97,TOdd coopeR,55,Female,A+,Diabetes,2022-12-10,Jason Price,Henderson-Taylor,UnitedHealthcare,21772.341399,459,Elective,2022-12-31,Ibuprofen,Normal,21
101,KaTiE hENry,70,Male,B+,Diabetes,2022-07-08,Roberto Petersen,Reed LLC,Aetna,7187.272346,402,Emergency,2022-07-25,Aspirin,Normal,17

In [ ]:
# Numeric
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Age,55500.0,51.539459,19.602454,13.00000,35.000000,52.000000,68.000000,89.000000
Billing Amount,55500.0,25539.316097,14211.454431,-2008.49214,13241.224652,25538.069376,37820.508436,52764.276736
Room Number,55500.0,301.134829,115.243069,101.00000,202.000000,302.000000,401.000000,500.000000

In [ ]:
# Categorical
for col in ["Gender", "Blood Type", "Admission Type", "Medical Condition", "Hospital"]:
    print(f"\nColumn: {col}")
    print(df[col].value_counts())
    print(df[col].value_counts(normalize=True) * 100)  # % distribution

Column: Gender
Gender
Male      27774
Female    27726
Name: count, dtype: int64
Gender
Male      50.043243
Female    49.956757
Name: proportion, dtype: float64

Column: Blood Type
Blood Type
A-     6969
A+     6956
AB+    6947
AB-    6945
B+     6945
B-     6944
O+     6917
O-     6877
Name: count, dtype: int64
Blood Type
A-     12.556757
A+     12.533333
AB+    12.517117
AB-    12.513514
B+     12.513514
B-     12.511712
O+     12.463063
O-     12.390991
Name: proportion, dtype: float64

Column: Admission Type
Admission Type
Elective     18655
Urgent       18576
Emergency    18269
Name: count, dtype: int64
Admission Type
Elective     33.612613
Urgent       33.470270
Emergency    32.917117
Name: proportion, dtype: float64

Column: Medical Condition
Medical Condition
Arthritis       9308
Diabetes        9304
Hypertension    9245
Obesity         9231
Cancer          9227
Asthma          9185
Name: count, dtype: int64
Medical Condition
Arthritis       16.771171
Diabetes        16.763964
Hypertension    16.657658
Obesity         16.632432
Cancer          16.625225
Asthma          16.549550
Name: proportion, dtype: float64

Column: Hospital
Hospital
LLC Smith                     44
Ltd Smith                     39
Johnson PLC                   38
Smith Ltd                     37
Smith PLC                     36
                              ..
Hammond Ltd                    1
Moran Smith and Galloway,      1
Winters Martin, and Neal       1
James-Owen                     1
Marks, and Vazquez Jenkins     1
Name: count, Length: 39876, dtype: int64
Hospital
LLC Smith                     0.079279
Ltd Smith                     0.070270
Johnson PLC                   0.068468
Smith Ltd                     0.066667
Smith PLC                     0.064865
                                ...
Hammond Ltd                   0.001802
Moran Smith and Galloway,     0.001802
Winters Martin, and Neal      0.001802
James-Owen                    0.001802
Marks, and Vazquez Jenkins    0.001802
Name: proportion, Length: 39876, dtype: float64

*La Cohérence Clinique (Médicaments vs Pathologie)*

On va chercher à Vérifier si les médicaments prescrits sont cohérents avec la maladie.
*Exemple de cas*  : On ne donne pas de la Pénicilline pour de l'Arthrite ou de l'Asthme (c'est un antibiotique). On ne donne pas d'Aspirine pour soigner un Cancer.

In [7]:

# Vérifier quels médicaments sont donnés pour l'Asthme
asthma_meds = df[df["Medical Condition"] == "Asthma"]["Medication"].value_counts()
print("Médicaments prescrits pour l'Asthme :\n", asthma_meds)

# Si on voit "Penicillin" ou "Lipitor" pour de l'Asthme, c'est une incohérence métier majeure.

Médicaments prescrits pour l'Asthme :
 Medication
Paracetamol    938
Penicillin     930
Lipitor        929
Ibuprofen      904
Aspirin        897
Name: count, dtype: int64

*La Logique Assurantielle (Age vs Assurance)*

Aux USA (contexte probable vu les noms d'assurances), Medicare est strictement réservé aux personnes de 65 ans et plus (sauf rares exceptions de handicap).

L'anomalie probable : Des patients jeunes (ex: 20 ans) couverts par Medicare.

In [8]:
# Cohérence Age vs Medicare
medicare_anomaly = df[
    (df["Insurance Provider"] == "Medicare") &
    (df["Age"] < 65)
]
print(f"Nombre de patients < 65 ans sous Medicare : {medicare_anomaly.shape[0]}")

Nombre de patients < 65 ans sous Medicare : 3776

*La Gestion des Chambres (Collisions Spatiales)*

Vérification de l'occupation temporelle des chambres.

Le problème physique : Une même chambre (ex: 101) ne peut pas être occupée par deux patients différents en même temps.

In [9]:
# Collision de chambres : Deux patients admis dans la même chambre le même jour
room_collision = df[df.duplicated(subset=["Room Number", "Date of Admission"], keep=False)]
print(f"Collisions de chambres détectées : {room_collision.shape[0]}")

Collisions de chambres détectées : 1040

*La Qualité des Textes (Problèmes de format)*

casse aléatoire : Compter combien de noms contiennent des majuscules au milieu du mot.

 les noms d'hôpitaux business : Chercher les suffixes "LLC" ou "Inc" qui ne devraient pas être là pour un hôpital.

In [10]:
# Détection de casse irrégulière (lettre majuscule au milieu d'un nom)
# Regex : une minuscule suivie d'une majuscule
irregular_case = df[df["Name"].str.contains(r'[a-z][A-Z]', regex=True)]
print(f"Noms avec casse mixte suspecte : {irregular_case.shape[0]}")

# Détection de suffixes commerciaux dans les hôpitaux
commercial_hospitals = df[df["Hospital"].str.contains(r' LLC| Inc| Ltd', regex=True)]
print(f"Hôpitaux avec noms commerciaux (LLC, Inc...) : {commercial_hospitals.shape[0]}")

Noms avec casse mixte suspecte : 27141
Hôpitaux avec noms commerciaux (LLC, Inc...) : 2305